---
# tasks file for deploy_apache_web

- name: Check and print Linux Version
  debug: var=ansible_os_family
- block:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    - name: Start Apache
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"
- name: Generate INDEX.HTML file
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
  notify:
    - Restart Apache
- name: Copy html file to webserver
  copy: src={{ item }} dest={{ destin_folder }} mode=0555
  loop:
    - "file.txt"
    - "file2.txt"
    - "file3.txt"
  notify:
    - Restart Apache
