---
- name: This Playbook will do autobackup on controller node
  hosts: localhost
  become: false

  vars_files:
    - ./group_vars/var.yml

  tasks:
    - name: Create backup folder
      file:
        path: "{{ ansible_dest_directory }}"
        state: directory
        mode: 0755
      run_once: true

    - name: Copy ansible backup directory
      copy:
        src: "{{ ansible_src_directory }}"
        dest: "{{ ansible_dest_directory }}"

    - name: Archive ansible backup directory
      community.general.archive:
        path: "{{ ansible_dest_directory }}/ansible"
        dest: "{{ ansible_dest_directory }}/ansible.tgz"
        remove: true

    - name: Copy ansible archive to googledrive
      shell:
        cmd: 'cp -r "{{ ansible_dest_directory }}/ansible.tgz" "{{ googledrive_dest_directory }}"'
