---
- name: This Playbook will do autobackup on controller node
  hosts: localhost
  become: false

  vars_files:
    - ./group_vars/var.yml

  tasks:
    - name: Create backup folder
      file:
        path: "{{ backup_dest_directory }}"
        state: directory
        mode: 0755
      run_once: true

    - name: Copy workspace to backup directory
      copy:
        src: "{{ workspace_src_directory }}"
        dest: "{{ backup_dest_directory }}"

    - name: Archive workspace backup directory
      community.general.archive:
        path: "{{ backup_dest_directory }}/workspace"
        dest: "{{ backup_dest_directory }}/workspace.tgz"
        remove: true

    - name: Copy workspace archive to googledrive
      shell:
        cmd: 'cp -r "{{ backup_dest_directory }}/workspace.tgz" "{{ workspace_googledrive_dest_directory }}"'
