---
# tasks file for main
- name: Deploy Apache task
  debug: var=ansible_os_family

- block:
    - name: Install Apache
      apt: name=apache2 state=latest

    - name: Start Apache
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"
- name: Generate j2 template
  template: src=index.j2 dest={{ dest_folder }}/index.html mode=0555
  notify: Restart Apache

- name: Copy files to webserver
  copy: src={{ item }} dest={{ dest_folder }} mode=0555
  loop:
    - "file.txt"
    - "file2.txt"
    - "file3.txt"
  notify:
    - Restart Apache
