---
- name: Create folder1
  file:
    path: /home/secret/fodler1
    state: directory
    mode: 0755

- name: Create folder2
  file:
    path: /home/secret/folder2
    state: directory
    mode: 0755
