---
- name: Prometheus manual installation
  hosts: DEV
  become: yes

  tasks:
    # Creating group&user
    - block:
        - name: Apt update
          apt:
            update_cache: true
          # Check group list
        - name: Get group
          getent:
            database: group
          # Check users list
        - name: Get User
          getent:
            database: passwd
          # List of groups
        - debug:
            var: ansible_facts.getent_group
          # List of users
        - debug:
            var: ansible_facts.getent_passwd

        - name: Set group prometheus
          group:
            name: prometheus
            gid: 137
          when:
            - "'prometheus' not in ansible_facts.getent_group"
            - "'137' not in item.value"
          loop: "{{ ansible_facts.getent_group | dict2items }}" # dict2items перебирает цикл по словарю

        - name: Set fact when prometheus user exists
          set_fact:
            user_exists: true
          when: '"prometheus" in item.key'
          loop: "{{ ansible_facts.getent_passwd | dict2items }}"
        - name: Set fact when prometheus user does not exists
          set_fact:
            user_exists: false
          when: '"prometheus" not in item.key'
          loop: "{{ ansible_facts.getent_passwd | dict2items }}"

        - name: Add User prometheus
          user:
            name: prometheus
            comment: Prometheus user
            uid: 130
            group: prometheus
            shell: /sbin/nologin
            system: true
            create_home: false
          when:
            - not user_exists
            - "'130' not in item.value[1]"
          loop: "{{ ansible_facts.getent_passwd | dict2items }}"

      when: ansible_os_family == "Debian"
      # Prepare folders and download prometheus
    - block:
        - name: Create folder /etc/
          file:
            path: /etc/prometheus
            state: directory
            owner: prometheus
            group: prometheus
            mode: 0755
        - name: Create folder /var/lib
          file:
            path: /var/lib/prometheus
            state: directory
            owner: prometheus
            group: prometheus
            mode: 0755

        # - name: Get prometheus from official site ?
        #   get_url:
        #     url: https://github.com/prometheus/prometheus/releases/download/v2.45.1/prometheus-2.45.1.linux-amd64.tar.gz
        #     dest: /home/dark/Downloads
        #     owner: prometheus
        #     mode: 0755
        #     checksum: sha256:48bdf3e6f0627a28ffb9efa15e6a7fee35bb320b98b060c901a856007cdf079d

        - name: Unzip prometheus
          unarchive:
            src: https://github.com/prometheus/prometheus/releases/download/v2.45.1/prometheus-2.45.1.linux-amd64.tar.gz
            remote_src: true
            dest: /home/dark/Downloads
            owner: prometheus
            mode: 0755
      when: ansible_os_family == "Debian"
      # Moving files to their folders
    - block:
        - name: Move Binary Files
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: prometheus
            group: prometheus
            mode: 0755
            remote_src: yes
          loop:
            - {
                src: "/home/dark/Downloads/prometheus-2.45.1.linux-amd64/prometheus",
                dest: "/usr/local/bin/prometheus",
              }
            - {
                src: "/home/dark/Downloads/prometheus-2.45.1.linux-amd64/promtool",
                dest: "/usr/local/bin/promtool",
              }

        - name: Move Config Files
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: prometheus
            group: prometheus
            mode: 0755
            remote_src: yes
          loop:
            - {
                src: "/home/dark/Downloads/prometheus-2.45.1.linux-amd64/consoles",
                dest: "/etc/prometheus/consoles",
              }
            - {
                src: "/home/dark/Downloads/prometheus-2.45.1.linux-amd64/console_libraries",
                dest: "/etc/prometheus/console_libraries",
              }
            - {
                src: "/home/dark/Downloads/prometheus-2.45.1.linux-amd64/prometheus.yml",
                dest: "/etc/prometheus/prometheus.yml",
              }
      when: ansible_os_family == "Debian"
      # Create Systemd service for prometheus and enable him
    - block:
        - name: Create prometheus.service file
          copy:
            dest: /etc/systemd/system/prometheus.service
            owner: prometheus
            group: prometheus
            mode: 0755
            content: |
              [Unit]
              Description=Prometheus
              Wants=network-online.target
              After=network-online.target

              [Service]
              User=prometheus
              Group=prometheus
              Restart=on-failure
              Type=simple

              ExecStart=/usr/local/bin/prometheus \
                  --config.file /etc/prometheus/prometheus.yml \
                  --storage.tsdb.path /var/lib/prometheus/ \
                  --web.console.templates=/etc/prometheus/consoles \
                  --web.console.libraries=/etc/prometheus/console_libraries

              [Install]
              WantedBy=multi-user.target
        - name: Systemd daemon reload
          systemd_service:
            daemon_reload: true
            name: prometheus
            state: started
            enabled: true
          notify:
            - Restart Prometheus Service

      when: ansible_os_family == "Debian"

  handlers:
    - name: Restart Prometheus Service
      systemd_service:
        name: prometheus
        state: restarted
