---
- name: Prometheus installation via apt-manager
  hosts: DEV
  become: true

  tasks:
    - block:
        - name: Apt update
          apt:
            update_cache: true
        - name: Install Prometheus
          apt:
            name: prometheus
            state: latest
        - name: Check Prometheus version
          shell:
            cmd: prometheus --version > promver && cat
          register: output
        - name: Print Prometheus version
          debug:
            var: output.stdout_lines
        - name: Replace config file
          copy:
            src: ./files/promfiles/prometheus.yml
            dest: /etc/prometheus/
            mode: 0777

        - name: Config Check
          shell: cat /etc/prometheus/prometheus.yml
          register: promout
        - name: Config output
          debug:
            var: promout.stdout_lines
      when: ansible_os_family == "Debian"
