---
- name: Install Apache and upload webpage
  hosts: STAGING_SERVERS
  become: yes

  vars:
    source_file: ./website/index.html
    destination_file: /var/www/html

  tasks:
    - name: Install Apache Web Server
      apt: name=apache2 state=latest

    - name: Copy homepage to STAGING_SERVERS
      copy: src={{ source_file }} dest={{ destination_file }} mode=0555
      notify: Restart Apache

    - name: Start Webserver and make it enable on boot
      service: name=apache2 state=started enabled=yes

  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
