---
- name: Install default Apache Web Server
  hosts: STAGING_SERVERS
  become: yes

  tasks:
    - name: Install Apache Web Server
      apt: name=apache2 state=latest

    - name: Start Apache ane Enable it on the boot
      service: name=apache2 state=started enabled=yes
