---
- name: Playbook 5
  hosts: linux1
  become: yes

  vars:
    source_folder: ./websiteetc
    destin_folder: /var/www/html

  tasks:
    - name: Check and print Linux Version
      debug: var=ansible_os_family

    - block:
        - name: Install Apache Webserver
          apt:
            name: apache2
            state: latest

        - name: Start Webserver service
          service: name=apache2 state=started enabled=yes

      when: ansible_os_family == "Debian"

    - name: Copy index.html to Webserver
      copy: src={{ item }} dest={{ destin_folder }} mode=0555
      with_fileglob: "{{ source_folder }}/*.*"
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
      when: ansible_os_family == "Debian"
