---
# tasks file for common
- name: Install Java v11
  apt: name=openjdk-11-jre-headless state=latest
# - name: Install Jenkins from bash script
#   shell: |
#     curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
#       /usr/share/keyrings/jenkins-keyring.asc > /dev/null
#     echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
#       https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
#       /etc/apt/sources.list.d/jenkins.list > /dev/null
#     sudo apt-get update
#     sudo apt-get install jenkins
#   args:
#     executable: /bin/sh
#   delegate_to: linux1
# - name: Install nginx server
#   apt: name=nginx state=latest
# - name: Add FireWall rule
#   shell: ufw allow 'Nginx HTTP'
# - name: Reload nginx server
#   service: name=nginx state=restarted enabled=yes
# - name: Copy nginx.cfg
# - fetch:
#     src: /etc/nginx/nginx.conf
#     dest: /home/dark/workspace/ansible/nginx
