---
- name: Playbook initialization monitoring system with docker
  hosts: DEV
  become: true

  roles:
    - { role: docker, when: ansible_system == "Linux" }
    - { role: prometheus, when: ansible_system == "Linux" }
